plugins:
  - jekyll-seo-tag

title: Kiet Tran's Portfolio

description: I'm currently a junior at Macalester College (class of 2020). I <3 software/web development and graphic design. Visit this site to know more about me and check out some of my projects :)